//Creative Vending Upgrade - Infinite Resources
mods.extendedcrafting.TableCrafting.addShaped(0, <storagedrawers:upgrade_creative:1> * 2, [
	[<ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <avaritia:resource:5>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>], 
	[<ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <storagedrawers:upgrade_void>, <ore:drawerBasic>, <ore:drawerBasic>, <ore:drawerBasic>, <storagedrawers:upgrade_void>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>], 
	[<ore:ingotCosmicNeutronium>, <storagedrawers:upgrade_void>, <ore:drawerBasic>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <ore:drawerBasic>, <storagedrawers:upgrade_void>, <ore:ingotCosmicNeutronium>], 
	[<ore:ingotCosmicNeutronium>, <ore:drawerBasic>, <mysticalagradditions:stuff:69>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <mysticalagradditions:stuff:69>, <ore:drawerBasic>, <ore:ingotCosmicNeutronium>], 
	[<avaritia:resource:5>, <ore:drawerBasic>, <mysticalagradditions:stuff:69>, <storagedrawers:upgrade_storage:4>, <extendedcrafting:frame>, <storagedrawers:upgrade_storage:4>, <mysticalagradditions:stuff:69>, <ore:drawerBasic>, <avaritia:resource:5>], 
	[<ore:ingotCosmicNeutronium>, <ore:drawerBasic>, <mysticalagradditions:stuff:69>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <mysticalagradditions:stuff:69>, <ore:drawerBasic>, <ore:ingotCosmicNeutronium>], 
	[<ore:ingotCosmicNeutronium>, <storagedrawers:upgrade_void>, <ore:drawerBasic>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <ore:drawerBasic>, <storagedrawers:upgrade_void>, <ore:ingotCosmicNeutronium>], 
	[<ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <storagedrawers:upgrade_void>, <ore:drawerBasic>, <ore:drawerBasic>, <ore:drawerBasic>, <storagedrawers:upgrade_void>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>], 
	[<ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <avaritia:resource:5>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>]
]);
