//Priority
#priority 1
//Import
import crafttweaker.item.IItemStack;
//Array (No particular order, too many items to do that)
val IArray = [<thermalfoundation:material:65>, <immersiveengineering:metal:18>, <immersiveengineering:metal:19>, <immersiveengineering:metal:9>, <immersiveengineering:metal:10>, <immersiveengineering:metal:11>, <immersiveengineering:metal:12>, <immersiveengineering:metal:13>, <immersiveengineering:metal:14>, <immersiveengineering:metal:15>, <immersiveengineering:metal:16>, <immersiveengineering:metal:17>, <techreborn:dust:10>, <minecraft:sand>, <minecraft:gravel>, <minecraft:string>, <thermalfoundation:material:770>, <thermalfoundation:material:768>, <thermalfoundation:material:103>, <thermalfoundation:material:102>, <thermalfoundation:material:101>, <thermalfoundation:material:98>, <thermalfoundation:material:72>, <thermalfoundation:material:71>, <minecraft:redstone>, <minecraft:glowstone_dust>, <minecraft:blaze_powder>, <minecraft:prismarine_crystals>, <actuallyadditions:item_dust:7>, <advancedrocketry:productdust>, <libvulpes:productdust>, <advancedrocketry:productdust:1>, <appliedenergistics2:material:2>, <appliedenergistics2:material:8>, <astralsorcery:itemcraftingcomponent:2>, <draconicevolution:draconium_dust>, <enderio:item_material:74>, <immersiveengineering:material:17>, <immersiveengineering:material:18>, <defiledlands:gravel_defiled>, <defiledlands:sand_defiled>, <defiledlands:hephaestite>, <defiledlands:scarlite>, <appliedenergistics2:material>, <appliedenergistics2:material:1>, <actuallyadditions:item_misc:5>, <minecraft:quartz>, <minecraft:emerald>, <minecraft:dye:4>, <minecraft:diamond>, <minecraft:coal>, <quark:biotite>, <rftools:dimensional_shard>, <astralsorcery:itemcraftingcomponent>, <thaumcraft:amber>, <techreborn:dust:54>, <thermalfoundation:material:70>, <nuclearcraft:dust:3>, <nuclearcraft:dust:5>, <nuclearcraft:dust:6>, <nuclearcraft:dust:7>, <nuclearcraft:dust_oxide:1>, <nuclearcraft:dust_oxide>, <nuclearcraft:dust:11>, <nuclearcraft:dust:10>, <nuclearcraft:dust:9>, <nuclearcraft:dust:8>, <nuclearcraft:dust_oxide:2>, <nuclearcraft:dust_oxide:3>, <nuclearcraft:gem_dust:1>, <nuclearcraft:gem_dust:4>, <nuclearcraft:gem_dust:5>, <nuclearcraft:gem_dust:8>, <nuclearcraft:gem_dust:9>, <minecraft:clay_ball>, <minecraft:dye:15>, <libvulpes:productdust:3>, <mekanism:otherdust:5>, <mekanism:dust:2>, <redstonearsenal:material>, <techreborn:dust:41>, <techreborn:dust:6>, <techreborn:dust:48>, <techreborn:dust:36>, <techreborn:dust:45>, <techreborn:dust:58>, <techreborn:dust:43>, <techreborn:dust:50>, <techreborn:dust:11>, <techreborn:gem:2>, <techreborn:gem:1>, <techreborn:gem>, <nuclearcraft:gem_dust>, <techreborn:dust:39>, <techreborn:dust:23>, <techreborn:dust:18>, <nuclearcraft:gem_dust:2>, <techreborn:dust:5>, <techreborn:dust:55>, <actuallyadditions:item_dust:4>, <thermalfoundation:material:99>, <techreborn:dust:59>, <techreborn:dust:31>] as IItemStack[];
//Function
for i, item in IArray {
mods.immersiveengineering.Crusher.removeRecipe(item);}
