//Removed Recipes
//Machines
///Thermal Expansion
recipes.remove(<thermalexpansion:machine:11>);
recipes.remove(<thermalexpansion:machine:9>);
recipes.remove(<thermalexpansion:machine:8>);
recipes.remove(<thermalexpansion:machine:6>);
recipes.remove(<thermalexpansion:machine:5>);
recipes.remove(<thermalexpansion:machine:3>);
recipes.remove(<thermalexpansion:machine:2>);
recipes.remove(<thermalexpansion:machine:1>);
recipes.remove(<thermalexpansion:machine>);
recipes.remove(<thermalexpansion:dynamo>);
recipes.remove(<thermalexpansion:dynamo:2>);
///Actually Additions
recipes.remove(<actuallyadditions:block_atomic_reconstructor>);
recipes.remove(<actuallyadditions:block_grinder_double>);
recipes.remove(<actuallyadditions:block_grinder>);
recipes.remove(<actuallyadditions:block_furnace_double>);
recipes.remove(<actuallyadditions:block_empowerer>);
recipes.remove(<actuallyadditions:block_bio_reactor>);
recipes.remove(<actuallyadditions:block_coal_generator>);
recipes.remove(<actuallyadditions:block_oil_generator>);
recipes.remove(<actuallyadditions:block_canola_press>);
recipes.remove(<actuallyadditions:block_fermenting_barrel>);
recipes.remove(<actuallyaddon:advanced_reconstructor>);
///Nuclearcraft
recipes.remove(<nuclearcraft:nuclear_furnace_idle>);
recipes.remove(<nuclearcraft:fission_controller_new_fixed>);
recipes.remove(<nuclearcraft:alloy_furnace_idle>);
recipes.remove(<nuclearcraft:manufactory_idle>);
recipes.remove(<nuclearcraft:pressurizer_idle>);
recipes.remove(<nuclearcraft:decay_generator>);
///Extra Utilities 2
recipes.remove(<extrautils2:resonator>);
recipes.remove(<extrautils2:analogcrafter>);
recipes.removeShapeless(<extrautils2:crafter>);
recipes.remove(<extrautils2:teleporter:1>);
recipes.remove(<extrautils2:passivegenerator:8>);
recipes.remove(<extrautils2:interactionproxy>);
recipes.removeByRecipeName("extrautils2:drum_16");
recipes.removeByRecipeName("extrautils2:drum_256");
recipes.removeByRecipeName("extrautils2:drum_4096");
recipes.removeByRecipeName("extrautils2:drum_65536");
///Draconic Evolution
recipes.remove(<draconicevolution:energy_storage_core>);
recipes.remove(<draconicevolution:crafting_injector>);
recipes.remove(<draconicevolution:fusion_crafting_core>);
///Extended Crafting
recipes.remove(<extendedcrafting:crafting_core>);
recipes.remove(<extendedcrafting:pedestal>);
recipes.remove(<extendedcrafting:table_basic>);
recipes.remove(<extendedcrafting:table_advanced>);
recipes.remove(<extendedcrafting:table_elite>);
recipes.remove(<extendedcrafting:table_ultimate>);
recipes.remove(<extendedcrafting:compressor>);
recipes.remove(<extendedcrafting:ender_alternator>);
recipes.remove(<extendedcrafting:ender_crafter>);
recipes.remove(<extendedcrafting:interface>);
///Mekanism
recipes.remove(<mekanism:machineblock:10>);
recipes.remove(<mekanism:machineblock:8>);
recipes.remove(<mekanism:machineblock:3>);
recipes.remove(<mekanism:machineblock>);
recipes.remove(<mekanismgenerators:generator:6>);
recipes.remove(<mekanismgenerators:generator:1>);
recipes.remove(<mekanismgenerators:generator:4>);
recipes.remove(<mekanismgenerators:generator:5>);
recipes.remove(<mekanism:transmitter>.withTag({tier: 0}));
recipes.remove(<mekanism:transmitter:1>.withTag({tier: 0}));
recipes.remove(<mekanism:transmitter:2>.withTag({tier: 0}));
recipes.remove(<mekanism:transmitter:3>.withTag({tier: 0}));
recipes.remove(<mekanism:transmitter:4>.withTag({tier: 0}));
recipes.remove(<mekanism:transmitter:6>.withTag({tier: 0}));
////Factories
recipes.remove(<mekanism:machineblock:7>);
recipes.remove(<mekanism:machineblock:7>);
recipes.remove(<mekanism:machineblock:7>);
recipes.remove(<mekanism:machineblock:7>);
recipes.remove(<mekanism:machineblock:7>);
recipes.remove(<mekanism:machineblock:7>);
recipes.remove(<mekanism:machineblock:7>);
recipes.remove(<mekanism:machineblock:7>);
recipes.remove(<mekanism:machineblock:6>);
recipes.remove(<mekanism:machineblock:6>);
recipes.remove(<mekanism:machineblock:6>);
recipes.remove(<mekanism:machineblock:6>);
recipes.remove(<mekanism:machineblock:6>);
recipes.remove(<mekanism:machineblock:5>);
recipes.remove(<mekanism:machineblock:5>);
recipes.remove(<mekanism:machineblock:5>);
recipes.remove(<mekanism:machineblock:5>);
recipes.remove(<mekanism:machineblock:5>);
recipes.remove(<mekanism:machineblock:5>);
recipes.remove(<mekanism:machineblock:5>);
recipes.remove(<mekanism:machineblock:5>);
recipes.remove(<mekanism:machineblock:5>);
recipes.remove(<mekanism:tierinstaller:3>);
recipes.remove(<mekanism:tierinstaller:2>);
recipes.remove(<mekanism:tierinstaller:1>);
recipes.remove(<mekanism:tierinstaller>);
///AE2
recipes.remove(<appliedenergistics2:inscriber>);
recipes.remove(<appliedenergistics2:molecular_assembler>);
recipes.remove(<appliedenergistics2:part:180>);
recipes.remove(<appliedenergistics2:controller>);
recipes.remove(<appliedenergistics2:charger>);
///Project E
recipes.remove(<projecte:transmutation_table>);
recipes.remove(<projecte:condenser_mk2>);
recipes.remove(<projecte:condenser_mk1>);
recipes.remove(<projecte:collector_mk1>);
recipes.remove(<projecte:collector_mk2>);
recipes.remove(<projecte:collector_mk3>);
recipes.remove(<projecte:relay_mk2>);
recipes.remove(<projecte:relay_mk3>);
recipes.remove(<projecte:relay_mk1>);
///RFtools
recipes.remove(<rftools:crafter3>);
recipes.remove(<rftools:crafter2>);
recipes.remove(<rftools:crafter1>);
///Ender IO
recipes.remove(<enderio:block_combustion_generator>);
recipes.remove(<enderio:block_powered_spawner>);
recipes.remove(<enderio:block_wired_charger>);
recipes.remove(<enderio:block_farm_station>);
recipes.remove(<enderio:block_crafter>);
recipes.remove(<enderio:block_stirling_generator>);
recipes.remove(<enderio:block_sag_mill>);
recipes.remove(<enderio:block_alloy_smelter>);
////Enhanced Machines
recipes.removeByRecipeName("enderio:enhanced_alloy_smelter");
recipes.removeByRecipeName("enderio:enhanced_combustion_generator");
recipes.removeByRecipeName("enderio:enhanced_s_a_g_mill");
recipes.removeByRecipeName("enderio:enhanced_vat");
recipes.removeByRecipeName("enderio:enhanced_wired_charger");
///Flux Networks
recipes.remove(<fluxnetworks:gargantuanfluxstorage>);
recipes.remove(<fluxnetworks:herculeanfluxstorage>);
recipes.remove(<fluxnetworks:fluxstorage>);
recipes.remove(<fluxnetworks:fluxcontroller>);
recipes.remove(<fluxnetworks:fluxpoint>);
recipes.remove(<fluxnetworks:fluxplug>);
///Industrial Foregoing
recipes.remove(<industrialforegoing:laser_base>);
recipes.remove(<industrialforegoing:laser_drill>);
recipes.remove(<industrialforegoing:latex_processing_unit>);
recipes.remove(<industrialforegoing:tree_fluid_extractor>);
recipes.remove(<industrialforegoing:conveyor>);
///Embers
recipes.remove(<embers:ember_bore>);
recipes.remove(<embers:block_furnace>);
recipes.remove(<embers:mixer>);
recipes.remove(<embers:stamper_base>);
recipes.remove(<embers:stamper>);
recipes.remove(<embers:item_pipe>);
recipes.remove(<embers:mech_core>);
///Tech Reborn
recipes.remove(<techreborn:vacuum_freezer>);
recipes.remove(<techreborn:industrial_blast_furnace>);
recipes.remove(<techreborn:alloy_smelter>);
recipes.remove(<techreborn:iron_alloy_furnace>);
recipes.remove(<techreborn:implosion_compressor>);
recipes.remove(<techreborn:compressor>);
///Mob Grinding Utils
recipes.remove(<mob_grinding_utils:fan>);
recipes.remove(<mob_grinding_utils:ender_inhibitor_on>);
recipes.remove(<mob_grinding_utils:xp_tap>);
recipes.remove(<mob_grinding_utils:tank_sink>);
recipes.remove(<mob_grinding_utils:tank>);
recipes.remove(<mob_grinding_utils:spikes>);
recipes.remove(<mob_grinding_utils:mob_swab>);
recipes.remove(<mob_grinding_utils:absorption_hopper>);
recipes.remove(<mob_grinding_utils:entity_conveyor>);
recipes.remove(<mob_grinding_utils:saw>);
///Other
recipes.remove(<avaritia:extreme_crafting_table>);
recipes.remove(<draconicevolution:grinder>);
recipes.remove(<draconicevolution:potentiometer>);
recipes.remove(<draconicevolution:diss_enchanter>);
recipes.remove(<advancedrocketry:blastbrick>);
recipes.remove(<advancedrocketry:arcfurnace>);
recipes.remove(<advancedrocketry:suitworkstation>);
recipes.remove(<advancedrocketry:observatory>);
recipes.remove(<advancedrocketry:platepress>);
recipes.remove(<advancedrocketry:warpmonitor>);
recipes.remove(<advancedrocketry:warpcore>);
recipes.remove(<immersiveengineering:stone_decoration:1>);
recipes.remove(<immersiveengineering:stone_decoration:10>);
recipes.remove(<immersiveengineering:stone_decoration>);
recipes.remove(<psi:programmer>);
recipes.remove(<psi:cad_assembler>);
recipes.remove(<advancedrocketry:precisionassemblingmachine>);
recipes.remove(<compactmachines3:fieldprojector>);
recipes.remove(<quark:pipe>);
recipes.remove(<mysticalagradditions:special>);
recipes.remove(<mysticalagradditions:special:1>);
recipes.remove(<mysticalagradditions:special:4>);
recipes.remove(<botania:rfgenerator>);
recipes.remove(<darkutils:trap_move_hyper>);
recipes.remove(<darkutils:trap_move_fast>);
recipes.remove(<darkutils:trap_move>);
//Chassi, Frames etc.
///Thermal Expansion
recipes.remove(<thermalexpansion:frame>);
recipes.remove(<thermalexpansion:frame:64>);
recipes.remove(<thermalexpansion:frame:128>);
///Nuclearcraft
recipes.remove(<nuclearcraft:part:10>);
recipes.remove(<nuclearcraft:part:12>);
///Other
recipes.remove(<mekanism:basicblock:8>);
recipes.remove(<teslacorelib:machine_case>);
recipes.remove(<techreborn:machine_frame>);
recipes.remove(<techreborn:machine_frame:1>);
recipes.remove(<techreborn:machine_frame:2>);
recipes.remove(<libvulpes:structuremachine>);
recipes.remove(<libvulpes:advstructuremachine>);
recipes.remove(<enderio:item_material>);
recipes.remove(<rftools:machine_frame>);
recipes.remove(<rftools:machine_base>);
recipes.remove(<extendedcrafting:frame>);
recipes.remove(<actuallyadditions:block_misc:9>);
recipes.remove(<extendedcrafting:interface>);
recipes.remove(<actuallyadditions:block_misc:4>);
//Reactors
///Actual Thing
recipes.remove(<nuclearcraft:fusion_core>);
recipes.remove(<mekanismgenerators:reactor>);
///Casing
recipes.remove(<nuclearcraft:fission_block>);
recipes.remove(<mekanismgenerators:reactor:1>);
//Items and blocks
///Misc
recipes.remove(<actuallyadditions:item_wings_of_the_bats>);
recipes.remove(<draconicevolution:wyvern_core>);
recipes.remove(<draconicevolution:draconic_core>);
recipes.remove(<extendedcrafting:material>);
recipes.remove(<extendedcrafting:material:36>);
recipes.remove(<ae2wtlib:infinity_booster_card>);
recipes.remove(<nuclearcraft:part>);
recipes.remove(<nuclearcraft:part:1>);
recipes.remove(<nuclearcraft:part:2>);
recipes.remove(<nuclearcraft:part:3>);
recipes.remove(<actuallyadditions:item_misc:7>);
recipes.remove(<actuallyadditions:item_misc:8>);
recipes.remove(<thermalfoundation:material:657>);
recipes.remove(<thermalfoundation:material:640>);
recipes.remove(<thermalfoundation:material:656>);
recipes.remove(<buildinggadgets:copypastetool>);
recipes.remove(<buildinggadgets:exchangertool>);
recipes.remove(<buildinggadgets:buildingtool>);
recipes.remove(<buildinggadgets:destructiontool>);
recipes.remove(<buildinggadgets:constructionpastecontainer>);
recipes.remove(<buildinggadgets:constructionpastecontainert2>);
recipes.remove(<buildinggadgets:constructionpastecontainert3>);
recipes.remove(<buildinggadgets:templatemanager>);
recipes.remove(<projecte:item.pe_covalence_dust:2>);
recipes.remove(<projecte:item.pe_covalence_dust:1>);
recipes.remove(<projecte:item.pe_covalence_dust>);
recipes.remove(<projecte:item.pe_philosophers_stone>);
recipes.remove(<projecte:item.pe_transmutation_tablet>);
recipes.remove(<mob_grinding_utils:saw_upgrade:2>);
recipes.remove(<mob_grinding_utils:saw_upgrade:5>);
recipes.remove(<hooked:microcrafting>);
recipes.remove(<advancedrocketry:ic:5>);
recipes.remove(<advancedrocketry:ic:4>);
recipes.remove(<advancedrocketry:ic:3>);
recipes.remove(<advancedrocketry:misc>);
recipes.remove(<fluxnetworks:fluxcore>);
recipes.remove(<fluxnetworks:fluxblock>);
recipes.remove(<fluxnetworks:fluxconfigurator>);
recipes.remove(<actuallyadditions:item_tele_staff>);
recipes.remove(<industrialforegoing:infinity_drill>);
recipes.remove(<openglider:hang_glider_part:1>);
recipes.remove(<openglider:hang_glider_part>);
recipes.remove(<actuallyadditions:item_mining_lens>);
recipes.remove(<dimensionaledibles:overworld_apple>);
recipes.remove(<dimensionaledibles:nether_apple>);
recipes.remove(<dimensionaledibles:ender_apple>);
recipes.remove(<dimensionaledibles:overworld_cake>);
recipes.remove(<dimensionaledibles:nether_cake>);
recipes.remove(<dimensionaledibles:end_cake>);
recipes.remove(<quark:soul_compass>);
recipes.removeByRecipeName("enderio:staff_of_travelling");
recipes.remove(<mirageorb:mirageorb>);
recipes.remove(<buildinggadgets:constructionblockpowder>);
recipes.remove(<techreborn:part:24>);
recipes.remove(<jaopca:item_geartungsten>);
recipes.remove(<opencomputers:material:2>);
recipes.remove(<appliedenergistics2:material:40>);
recipes.remove(<defiledlands:ravaging_ingot>);
////Infusion Crystals
recipes.remove(<mysticalagriculture:master_infusion_crystal>);
recipes.remove(<mysticalagriculture:infusion_crystal>);
////Seeds
recipes.remove(<mysticalagradditions:nether_star_seeds>);
recipes.remove(<mysticalagradditions:dragon_egg_seeds>);
recipes.remove(<mysticalagradditions:awakened_draconium_seeds>);
///Circuits
recipes.remove(<mekanism:controlcircuit:3>);
recipes.remove(<mekanism:controlcircuit:1>);
recipes.remove(<mekanism:controlcircuit:2>);
///Wings
recipes.remove(<wings:dragon_wings>);
recipes.remove(<wings:evil_wings>);
recipes.remove(<wings:fairy_wings>);
recipes.remove(<wings:bat_wings>);
recipes.remove(<wings:fire_wings>);
recipes.remove(<wings:monarch_butterfly_wings>);
recipes.remove(<wings:blue_butterfly_wings>);
recipes.remove(<wings:slime_wings>);
recipes.remove(<wings:angel_wings>);
///Armour
recipes.remove(<enderio:item_end_steel_boots>);
recipes.remove(<enderio:item_end_steel_leggings>);
recipes.remove(<enderio:item_end_steel_chestplate>);
recipes.remove(<enderio:item_end_steel_helmet>);
recipes.remove(<enderio:item_dark_steel_boots>);
recipes.remove(<enderio:item_dark_steel_leggings>);
recipes.remove(<enderio:item_dark_steel_chestplate>);
recipes.remove(<enderio:item_dark_steel_helmet>);
recipes.remove(<enderio:item_stellar_alloy_boots>);
recipes.remove(<enderio:item_stellar_alloy_leggings>);
recipes.remove(<enderio:item_stellar_alloy_chestplate>);
recipes.remove(<enderio:item_stellar_alloy_helmet>);
recipes.remove(<botania:terrasteelboots>);
recipes.remove(<botania:terrasteellegs>);
recipes.remove(<botania:terrasteelchest>);
recipes.remove(<botania:terrasteelhelm>);
recipes.removeByRecipeName("botania:terrasteelhelmreveal");
recipes.remove(<draconicevolution:wyvern_boots>);
recipes.remove(<draconicevolution:wyvern_legs>);
recipes.remove(<draconicevolution:wyvern_chest>);
recipes.remove(<draconicevolution:wyvern_helm>);
recipes.remove(<advancedrocketry:spaceboots>);
recipes.remove(<advancedrocketry:spaceleggings>);
recipes.remove(<advancedrocketry:spacechestplate>);
recipes.remove(<advancedrocketry:spacehelmet>);
///Tools
recipes.remove(<draconicevolution:wyvern_pick>);
recipes.remove(<draconicevolution:wyvern_axe>);
recipes.remove(<draconicevolution:wyvern_bow>);
recipes.remove(<draconicevolution:wyvern_sword>);
recipes.remove(<draconicevolution:wyvern_shovel>);
recipes.remove(<botania:terraaxe>);
recipes.remove(<botania:terrapick>);
recipes.remove(<botania:crystalbow>);
recipes.remove(<botania:terrasword>);
recipes.remove(<botania:starsword>);
recipes.remove(<botania:thundersword>);
recipes.remove(<defiledlands:ravaging_shovel>);
recipes.remove(<defiledlands:ravaging_pickaxe>);
recipes.remove(<defiledlands:ravaging_axe>);
recipes.remove(<defiledlands:the_ravager>);
recipes.remove(<defiledlands:tears_shulker>);
recipes.remove(<defiledlands:tears_flame>);
recipes.remove(<defiledlands:calling_stone>);
recipes.remove(<defiledlands:idol_sorrow>);
recipes.remove(<libvulpes:linker>);
///Baubles
recipes.remove(<botania:supercloudpendant>);
recipes.remove(<botania:supertravelbelt>);
recipes.remove(<botania:travelbelt>);
recipes.remove(<botania:cloudpendant>);
recipes.remove(<botania:flighttiara>);
recipes.remove(<hooked:hook>);
recipes.remove(<hooked:hook:1>);
recipes.remove(<hooked:hook:2>);
recipes.remove(<hooked:hook:3>);
recipes.remove(<hooked:hook:4>);
recipes.remove(<defiledlands:phytoprostasia_amulet>);
recipes.remove(<defiledlands:scarlite_ring>);
recipes.remove(<advancedrocketry:jetpack>);
///Plates etc.
////Plates
recipes.removeByRecipeName("thaumcraft:voidplate");
recipes.removeByRecipeName("thaumcraft:thaumiumplate");
recipes.removeByRecipeName("immersiveengineering:compat/plate_thaumium_void");
recipes.removeByRecipeName("immersiveengineering:compat/plate_thaumium_thaumium");
////Rods
recipes.removeByRecipeName("immersiveengineering:material/stick_iron");
recipes.removeByRecipeName("immersiveengineering:material/stick_steel");
recipes.removeByRecipeName("immersiveengineering:material/stick_aluminum");
recipes.removeByRecipeName("advancedrocketry:ironstick");
recipes.removeByRecipeName("advancedrocketry:stickcopper");
recipes.removeByRecipeName("advancedrocketry:sticksteel");
recipes.removeByRecipeName("advancedrocketry:sticktitanium");
recipes.removeByRecipeName("advancedrocketry:stickiridium");
recipes.removeByRecipeName("advancedrocketry:sticktitaniumiridium");
recipes.removeByRecipeName("advancedrocketry:sticktitaniumaluminide");
///Gears
recipes.remove(<embers:gear_dawnstone>);
recipes.remove(<thaumicperiphery:gear_brass>);
recipes.remove(<libvulpes:productgear:7>);
recipes.remove(<advancedrocketry:productgear:1>);
recipes.remove(<advancedrocketry:productgear>);
recipes.remove(<jaopca:item_gearquartz>);
recipes.remove(<jaopca:item_gearchargedcertusquartz>);
recipes.remove(<jaopca:item_gearosmium>);
recipes.remove(<redstonearsenal:material:96>);
///AE2 Cells
////Housing
recipes.removeByRecipeName("appliedenergistics2:network/cells/empty_storage_cell");
recipes.removeByRecipeName("extracells:storagecells/case/item");
recipes.removeByRecipeName("extracells:storagecells/case/fluid");
recipes.removeByRecipeName("extracells:storagecells/case/gas");
recipes.removeByRecipeName("extracells:storagecells/fluid/e2acasing");
recipes.removeByRecipeName("extracells:storagecells/fluid/a2ecasing");
////Item
recipes.removeByRecipeName("appliedenergistics2:network/cells/storage_cell_1k");
recipes.removeByRecipeName("appliedenergistics2:network/cells/storage_cell_4k");
recipes.removeByRecipeName("appliedenergistics2:network/cells/storage_cell_16k");
recipes.removeByRecipeName("appliedenergistics2:network/cells/storage_cell_64k");
recipes.removeByRecipeName("extracells:storagecells/item/owncasing/256k");
recipes.removeByRecipeName("extracells:storagecells/item/owncasing/1024k");
recipes.removeByRecipeName("extracells:storagecells/item/owncasing/4096k");
recipes.removeByRecipeName("extracells:storagecells/item/owncasing/16384k");
////Fluid
recipes.removeByRecipeName("appliedenergistics2:network/cells/fluid_cell_1k");
recipes.removeByRecipeName("appliedenergistics2:network/cells/fluid_cell_4k");
recipes.removeByRecipeName("appliedenergistics2:network/cells/fluid_cell_16k");
recipes.removeByRecipeName("appliedenergistics2:network/cells/fluid_cell_64k");
recipes.removeByRecipeName("extracells:storagecells/fluid/owncasing/256k");
recipes.removeByRecipeName("extracells:storagecells/fluid/owncasing/1024k");
recipes.removeByRecipeName("extracells:storagecells/fluid/owncasing/4096k");
////Gas
recipes.removeByRecipeName("extracells:storagecells/gas/owncasing/1k");
recipes.removeByRecipeName("extracells:storagecells/gas/owncasing/4k");
recipes.removeByRecipeName("extracells:storagecells/gas/owncasing/16k");
recipes.removeByRecipeName("extracells:storagecells/gas/owncasing/64k");
recipes.removeByRecipeName("extracells:storagecells/gas/owncasing/256k");
recipes.removeByRecipeName("extracells:storagecells/gas/owncasing/1024k");
recipes.removeByRecipeName("extracells:storagecells/gas/owncasing/4096k");
///Removeall functions
mods.avaritia.ExtremeCrafting.removeAll();
